# Generated by Django 4.2.1 on 2023-05-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learninglogger_app', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='text',
            new_name='hello',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date_added',
            new_name='world',
        ),
    ]
