# Generated by Django 4.2.1 on 2023-05-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log_app', '0003_rename_text_topic_hello_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='world',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='hello',
            new_name='text',
        ),
    ]
